name: 'Deploy to Launchpad'
author: 'Stefan Löffler'
description: 'Upload packages to Launchpad PPAs'

inputs:
  changes_files:
    description: 'space-separated list of paths to .changes files to upload'
    required: true
  devel-repo:
    description: 'PPA to upload development versions to (e.g., ppa:testuser/nighlies)'
    required: true
  stable-repo:
    description: 'PPA to upload releases (tags) to (e.g., ppa:testuser/stable)'
    required: true

runs:
  using: composite
  steps:
    - run: |
        case "${GITHUB_REF}" in
          refs/tags/*)
            REPO="${{ inputs.stable-repo }}"
            ;;
          *)
            REPO="${{ inputs.devel-repo }}"
            ;;
        esac
        echo "::group::Uploading ${{ inputs.changes_files }}"
        # FIXME: Bypass HTTPS certificate verification as Launchpad supplies an invalid CN
        #cat /usr/bin/dput
        #sudo sed -i '5s/^/import ssl\nssl._create_default_https_context = ssl._create_unverified_context\n/' /usr/bin/dput
        #cat /usr/bin/dput
        dput -c .github/actions/deploy-launchpad/dput.cf ${REPO} ${{ inputs.changes_files }}
        echo "::endgroup::"
        done
      shell: bash
